#
# Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
#

apiVersion: v1
kind: Service
metadata:
  name: rest-inventory
  labels:
    run: rest-inventory
spec:
  ports:
  - name: http
    protocol: TCP
    port: 30100
    targetPort: 8080
  selector:
    run: rest-inventory
  sessionAffinity: None
type: LoadBalancer
