#
# Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
#

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    run: mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      run: mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      containers:
      - image: mongo:3.2.8
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    run: mongodb
spec:
  ports:
  - name: http
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    run: mongodb
  sessionAffinity: None
  type: NodePort
